// Code generated by goctl. DO NOT EDIT.
package types

type UserListReq struct {
	Pagination
	Sex string `form:"sex,options=M|F|O,optional"`
}

type UserListItem struct {
	ID int64 `json:"id"`
}

type UserListRes struct {
	Total int64           `json:"total"`
	Data  []*UserListItem `json:"data"`
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Pagination struct {
	Page     int64 `form:"page,optional,default=1"`
	PageSize int64 `form:"page_size,optional,default=10"`
}
